### ISSUE TITLE
这个能显示分割结果的边界吗？

### ISSUE THREAD

**Issue by mamemoryyy111** [imaginistLi/MiniViewer#1]

**Comment by imaginistLi** [comment]
你的意思是说你的模型预测结果的边界吗？如果是这样的话，你只需要将分割结果二值化，然后再导入就行了，也可以直接修改我的代码，就是在导入预测概率图之后加一个二值化的操作，例如： pred = pred > 0.5

**Comment by mamemoryyy111** [comment]
好的，我研究看看你的代码，如果没弄明白还得请教你
