### ISSUE TITLE
读取label的时候报错

### ISSUE THREAD

**Issue by chenxiahan** [imaginistLi/MiniViewer#2]
读取label的时候出现了这样一个报错：
希望可以解决~~
E:\MiniViewer-master>python main.py
F:/plain_scanCT_pancreatic_cancer/have_mask_nii/npy/image0/0112.npy
self.image_data.shape: (512, 512, 266)
F:/plain_scanCT_pancreatic_cancer/have_mask_nii/npy/mask0/0112.npy
self.label_data.shape: (512, 512, 266)
main.py:137: RuntimeWarning: invalid value encountered in true_divide
  img = np.uint8((img - img.min()) / img.ptp() * 255.0)
Traceback (most recent call last):
  File "main.py", line 132, in open_label_file
    self.label_refresh()
  File "main.py", line 138, in label_refresh
    myqimage = QtGui.QImage(img, img.shape[1], img.shape[0], img.strides[0], QtGui.QImage.Format_Indexed8)
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(QSize, QImage.Format): argument 1 has unexpected type 'numpy.ndarray'
  QImage(int, int, QImage.Format): argument 1 has unexpected type 'numpy.ndarray'
  QImage(bytes, int, int, QImage.Format): argument 1 has unexpected type 'numpy.ndarray'
  QImage(sip.voidptr, int, int, QImage.Format): argument 1 has unexpected type 'numpy.ndarray'
  QImage(bytes, int, int, int, QImage.Format): argument 1 has unexpected type 'numpy.ndarray'
  QImage(sip.voidptr, int, int, int, QImage.Format): argument 1 has unexpected type 'numpy.ndarray'
  QImage(List[str]): argument 1 has unexpected type 'numpy.ndarray'
  QImage(str, format: str = None): argument 1 has unexpected type 'numpy.ndarray'
  QImage(QImage): argument 1 has unexpected type 'numpy.ndarray'
  QImage(Any): too many arguments

**Comment by imaginistLi** [comment]
问题解决了，请参考https://stackoverflow.com/questions/48639185/pyqt5-qimage-from-numpy-array
